[project]
name = "railway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "mcp>=1.26.0",
    "playwright>=1.58.0",
    "pydantic>=2.12.5",
]
